language: php

php:
  - 5.6
  - 7.0
  - 7.1

install: composer install --dev

before_install:
  - sudo add-apt-repository ppa:mc3man/trusty-media
  - sudo apt-get update
  - sudo aptitude -y -q install ffmpeg

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/coveralls -v

notifications:
  email:
    on_success: never
